version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - mvn --version

  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - echo Packaging Lambda artifact...
      - cp target/events-sync-lambda.jar

artifacts:
  files:
    - target/*.jar
