version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Using pre-installed Maven..."
      - mvn --version

  pre_build:
    commands:
      - echo Resolving dependencies...
      - mvn install -DskipTests

  build:
    commands:
      - echo Building the project...
      - mvn clean package

  post_build:
    commands:
      - echo Uploading package to S3...
      - aws s3 cp target/events-import-lambda.jar s3://columbusimports3/events-import-lambda.jar
      - echo Deploying to Lambda function...
      - aws lambda update-function-code --function-name ColumbusEventsImportFunction --s3-bucket columbusimports3 --s3-key events-import-lambda.jar
      - echo Lambda function has been deployed

artifacts:
  files:
    - target/events-import-lambda.jar
#    - jar.sha256
  discard-paths: yes

cache:
  paths:
    - ~/.m2/**/*
