version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Using Java 17...
      - java -version
      - mvn --version

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Build finished, showing target dir...
      - ls -lh target/

artifacts:
  files:
    - target/events-sync-lambda.jar
  discard-paths: yes
