version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Using Java 17...
      - java -version
      - mvn --version

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Packaging Lambda artifact...
      - mkdir -p output
      - cp target/events-sync-lambda.jar output/

artifacts:
  files:
    - output/events-sync-lambda.jar
