version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Using pre-installed Maven..."
      - mvn --version

  pre_build:
    commands:
      - echo Resolving dependencies...
      - mvn install -DskipTests

  build:
    commands:
      - echo Building the project...
      - mvn clean package

  post_build:
    commands:
      - echo Uploading package to S3...
      - aws s3 cp target/events-import-lambda.jar s3://columbusimports3/events-import-lambda.jar
      - echo Deploying to Lambda function...
      - aws lambda update-function-code --function-name ColumbusEventsImportFunction --s3-bucket columbusimports3 --s3-key events-import-lambda.jar
      - echo Lambda function has been deployed

#      - echo "Verifying JAR contents..."
#      - "jar tf target/events-sync-lambda.jar | grep -E '^org/columbusEventsImportLambda/ImportServiceHandler\\.class$' || (echo 'ERROR: Handler class not found in JAR!' && exit 1)"
#      - echo "Computing SHA256 for deployed JAR..."
#      - "sha256sum target/events-sync-lambda.jar | tee jar.sha256"
#      - echo "Listing target dir:"
#      - ls -lh target/


artifacts:
  files:
    - target/*.jar
#    - jar.sha256
  discard-paths: yes

cache:
  paths:
    - ~/.m2/**/*
